### ISSUE TITLE
Getting this with all commands I've tried except `touch`. Any tips?

### ISSUE THREAD

**Issue by khord** [KhasMek/KhasBaht#1]
APP [10:26 PM] 
[ls] I had a problem handling "ls"

```Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/slackbot/dispatcher.py", line 55, in _dispatch_msg_handler
    func(Message(self._client, msg), *args)
  File "/home/pi/KhasBaht/khasbaht/plugins/fileutils.py", line 17, in ls
    cmd_runner(cmd, message)
  File "/home/pi/KhasBaht/khasbaht/helpers.py", line 26, in cmd_runner
    results = subprocess.run(cmd, stdout=subprocess.PIPE,
AttributeError: 'module' object has no attribute 'run'```

**Comment by khord** [comment]
Found the problem. Python 3.4 wasn't enough, needed to use Python 3.5.x

**Comment by KhasMek** [comment]
Awesome man, I'm glad you sorted it out so quickly. I'll add a note to the readme/install that it needs Python 3.5+.
